SERIES_REGISTRY = {'global_crude_oil': {'series_id': 'global_crude_oil',
                      'source': 'ceic',
                      'source_key': '42651501',
                      'label': 'Crude Oil',
                      'unit': 'USD/Barrel',
                      'frequency': 'Daily'},
 'global_us_natural_gas': {'series_id': 'global_us_natural_gas',
                           'source': 'ceic',
                           'source_key': '40780401',
                           'label': 'US Natural Gas',
                           'unit': 'USD/MM BTU',
                           'frequency': 'Daily'},
 'global_germany_natural_gas': {'series_id': 'global_germany_natural_gas',
                                'source': 'ceic',
                                'source_key': '449519797',
                                'label': 'Germany Natural Gas',
                                'unit': 'USD/MM BTU',
                                'frequency': 'Daily'},
 'global_japan_naphtha': {'series_id': 'global_japan_naphtha',
                          'source': 'ceic',
                          'source_key': '161345001',
                          'label': 'Japan Naphtha',
                          'unit': 'USD/Barrel',
                          'frequency': 'Monthly'},
 'global_france_naphtha': {'series_id': 'global_france_naphtha',
                           'source': 'ceic',
                           'source_key': '352664901',
                           'label': 'France Naphtha',
                           'unit': 'USD/Ton',
                           'frequency': 'Monthly'},
 'sea_cargo_handled': {'series_id': 'sea_cargo_handled',
                       'source': 'ceic',
                       'source_key': '36680501',
                       'label': 'Sea Cargo Handled',
                       'unit': 'Ton th',
                       'frequency': 'Monthly'},
 'container_throughput': {'series_id': 'container_throughput',
                          'source': 'ceic',
                          'source_key': '36681201',
                          'label': 'Container Throughput',
                          'unit': 'TEU th',
                          'frequency': 'Monthly'},
 'air_flight_movements': {'series_id': 'air_flight_movements',
                          'source': 'ceic',
                          'source_key': '36670301',
                          'label': 'Flight Movements',
                          'unit': 'Unit',
                          'frequency': 'Monthly'},
 'air_passenger_movements': {'series_id': 'air_passenger_movements',
                             'source': 'ceic',
                             'source_key': '241774802',
                             'label': 'Passenger Movements',
                             'unit': 'Person',
                             'frequency': 'Monthly'},
 'air_freight_movements': {'series_id': 'air_freight_movements',
                           'source': 'ceic',
                           'source_key': '241774902',
                           'label': 'Air Freight Movements',
                           'unit': 'Ton',
                           'frequency': 'Monthly'},
 'financial_sgx_turnover': {'series_id': 'financial_sgx_turnover',
                            'source': 'ceic',
                            'source_key': '35960701',
                            'label': 'SGX Daily Turnover',
                            'unit': 'Share mn',
                            'frequency': 'Daily'},
 'financial_forex_turnover': {'series_id': 'financial_forex_turnover',
                              'source': 'ceic',
                              'source_key': '471805317',
                              'label': 'Forex Monthly Turnover',
                              'unit': 'SGD mn',
                              'frequency': 'Monthly'},
 'financial_sora_3m': {'series_id': 'financial_sora_3m',
                       'source': 'ceic',
                       'source_key': '468026967',
                       'label': 'SORA 3M Compounded',
                       'unit': '% pa',
                       'frequency': 'Daily'},
 'financial_yield_2y': {'series_id': 'financial_yield_2y',
                        'source': 'ceic',
                        'source_key': '35945301',
                        'label': 'MAS Yield 2Y',
                        'unit': '% pa',
                        'frequency': 'Daily'},
 'financial_yield_10y': {'series_id': 'financial_yield_10y',
                         'source': 'ceic',
                         'source_key': '35945601',
                         'label': 'MAS Yield 10Y',
                         'unit': '% pa',
                         'frequency': 'Daily'},
 'visitor_arrival_land': {'series_id': 'visitor_arrival_land',
                          'source': 'ceic',
                          'source_key': '36588001',
                          'label': 'Visitor Arrivals by Land',
                          'unit': 'Person',
                          'frequency': 'Monthly'},
'food_and_beverage_sales': {'series_id': 'food_and_beverage_sales',
                          'source': 'ceic',
                          'source_key': '720061197',
                          'label': 'Food and Beverage Services Value (2025=100)',
                          'unit': 'Index',
                          'frequency': 'Monthly'}}
